name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: install deps
       run: npm ci

     - name: run tests
       run: npm test
    

  BuildDocker:
    needs: Test
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.divsphere.net/rose/div-c_server:latest

    - name: Login into harbor.divsphere.net
      run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login -u  ${{secrets.HARBOR_USERNAME }} --password-stdin harbor.divsphere.net

    - name: push image
      run: docker push harbor.divsphere.net/rose/div-c_server:latest
